services:
  node:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    init: true
    environment:
      - DATABASE_URL=postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@postgres:${DATABASE_PORT}/${DATABASE_NAME}
    env_file:
      - .env
    depends_on:
      - postgres
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/app
      - /app/node_modules
  postgres:
    image: postgres:16
    restart: unless-stopped
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - TZ=${TZ}
      - PGTZ=${TZ}
    volumes:
      - postgres:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin:/var/lib/pgadmin
volumes:
  postgres:
    driver: local
  pgadmin:
    driver: local
